FROM python:3.11-slim
WORKDIR /app
COPY python_functions/funcs /app/funcs
COPY python_functions/main.py /app/main.py
CMD ["python", "/app/main.py"]  # standaard CMD, kan door executor overschreven worden