[package]
name = "rust_functions"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Specificeer alle binaries

[[bin]]
name = "add_random_score"
path = "src/bin/add_random_score.rs"

[[bin]]
name = "is_adult"
path = "src/bin/is_adult.rs"